# Generated by Django 4.1.1 on 2022-10-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='login_id',
            new_name='username',
        ),
    ]
