# Generated by Django 4.1.2 on 2022-10-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.TextField(max_length=16, null=True),
        ),
    ]
